slice_name: "Average Heat-Pump Power vs Outdoor Temperature (5\xB0C bins)"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 3__table
  viz_type: echarts_timeseries_bar
  x_axis: bin_start
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: avg_power_w
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 32
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: Nullable(Float64)
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(avg_power_w)
    optionName: metric_0yzypkn9t7lp_zerub9miu4
  groupby:
  - bin_end
  adhoc_filters: []
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  annotation_layers: []
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"bin_start","label":"bin_start","expressionType":"SQL"},"bin_end"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg_power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":32,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(avg_power_w)","optionName":"metric_0yzypkn9t7lp_zerub9miu4"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg_power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":32,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(avg_power_w)","optionName":"metric_0yzypkn9t7lp_zerub9miu4"},false]],"annotation_layers":[],"row_limit":1000,"series_columns":["bin_end"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["bin_start"],"columns":["bin_end"],"aggregates":{"AVG(avg_power_w)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"AVG(avg_power_w)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"3__table","viz_type":"echarts_timeseries_bar","x_axis":"bin_start","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg_power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":32,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(avg_power_w)","optionName":"metric_0yzypkn9t7lp_zerub9miu4"}],"groupby":["bin_end"],"adhoc_filters":[],"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"annotation_layers":[],"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 57e7acfa-2151-4b1b-813b-80733eba7450
version: 1.0.0
dataset_uuid: 591aa66d-e666-458b-acae-0676b852e540
