slice_name: "Energy Use vs Temp Difference (Indoor \u2013 Outdoor)"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_scatter
params:
  datasource: 5__table
  viz_type: echarts_timeseries_scatter
  slice_id: 4
  x_axis: temp_delta
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: power_w
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 41
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: Nullable(Float64)
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(power_w)
    optionName: metric_de4fkwxbe2e_em2rq4rb97c
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  only_total: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"temp_delta","label":"temp_delta","expressionType":"SQL"}],"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":41,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(power_w)","optionName":"metric_de4fkwxbe2e_em2rq4rb97c","sqlExpression":null}],"orderby":[[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":41,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(power_w)","optionName":"metric_de4fkwxbe2e_em2rq4rb97c","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["temp_delta"],"columns":[],"aggregates":{"AVG(power_w)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"5__table","viz_type":"echarts_timeseries_scatter","slice_id":4,"x_axis":"temp_delta","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":41,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(power_w)","optionName":"metric_de4fkwxbe2e_em2rq4rb97c","sqlExpression":null}],"groupby":[],"adhoc_filters":[],"order_desc":true,"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"only_total":true,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7dd5c07d-2e95-4fd5-99dc-dfe7227e4d6e
version: 1.0.0
dataset_uuid: 6579ec9a-054d-4ea5-8edb-c4087af8e21a
