slice_name: How much do price fluctuations impact cost?
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 4__table
  viz_type: echarts_timeseries_line
  x_axis: price_bin_eur
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: bucket_cost
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 38
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: Nullable(Float64)
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(bucket_cost)
    optionName: metric_6rjkorp18jk_wocqzl503fi
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: energy_kwh
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 37
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: Nullable(Float64)
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(energy_kwh)
    optionName: metric_ut9kygft2ba_y8qdvocsbh
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: avg_power_w
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 36
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: Nullable(Float64)
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(avg_power_w)
    optionName: metric_zyw6074kvg9_c31y62sivsw
  groupby: []
  adhoc_filters: []
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":4,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"price_bin_eur","label":"price_bin_eur","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"bucket_cost","description":null,"expression":null,"filterable":true,"groupby":true,"id":38,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(bucket_cost)","optionName":"metric_6rjkorp18jk_wocqzl503fi"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"energy_kwh","description":null,"expression":null,"filterable":true,"groupby":true,"id":37,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(energy_kwh)","optionName":"metric_ut9kygft2ba_y8qdvocsbh"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg_power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":36,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(avg_power_w)","optionName":"metric_zyw6074kvg9_c31y62sivsw"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"bucket_cost","description":null,"expression":null,"filterable":true,"groupby":true,"id":38,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(bucket_cost)","optionName":"metric_6rjkorp18jk_wocqzl503fi"},false]],"annotation_layers":[],"row_limit":1000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["price_bin_eur"],"columns":[],"aggregates":{"AVG(bucket_cost)":{"operator":"mean"},"AVG(energy_kwh)":{"operator":"mean"},"AVG(avg_power_w)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"4__table","viz_type":"echarts_timeseries_line","x_axis":"price_bin_eur","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"bucket_cost","description":null,"expression":null,"filterable":true,"groupby":true,"id":38,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(bucket_cost)","optionName":"metric_6rjkorp18jk_wocqzl503fi"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"energy_kwh","description":null,"expression":null,"filterable":true,"groupby":true,"id":37,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(energy_kwh)","optionName":"metric_ut9kygft2ba_y8qdvocsbh"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg_power_w","description":null,"expression":null,"filterable":true,"groupby":true,"id":36,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Nullable(Float64)","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(avg_power_w)","optionName":"metric_zyw6074kvg9_c31y62sivsw"}],"groupby":[],"adhoc_filters":[],"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"annotation_layers":[],"x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"seriesType":"line","only_total":true,"opacity":0.2,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 591c2ad4-30ce-44a3-abb1-351e3d2da4aa
version: 1.0.0
dataset_uuid: d05b3cf1-3e2b-4ffa-8c2d-fbb3c30406dc
